### ISSUE TITLE
Devolutiva

### ISSUE THREAD

**Issue by JoaoRoccella** [rick-png/avaliacao-frontend#1]
Excelente trabalho, Enrick! A+++
Gostaria de fazer algumas sugestões para o futuro:
![image](https://github.com/rick-png/avaliacao-frontend/assets/5804196/bc8c8fe1-1d2a-48cd-b742-d9be7f6603b2)
Nesse bloco de texto, sugiro que o "Olá, eu sou" poderia seguir o alinhamento dos demais textos, à direita (end), como na imagem.

![image](https://github.com/rick-png/avaliacao-frontend/assets/5804196/d744c35d-63a1-42e8-a6c4-fe0fa640a389)
E aqui uma dúvida: foi uma decisão de design deixar o rodapé propositalmente com 80% da largura? Fiquei na dúvida, porque você está alinhando o body com ``` flex-direction: column``` mas tem um  ``` align-self: flex-end; ``` no footer. 

Parabéns!

**Comment by enrick-dev** [comment]
foi decisão de design mesmo, no body coloquei o flex-direction: column, o que resulta em o align-self: flex-end; ter um efeito ao contrario, ou seja, ao invés de jogar ao final do container em vertical, ele vai jogar ao final em horizontal. Por isso que está jogando para a direita

**Comment by JoaoRoccella** [comment]
Muito bom!
